---
- name: Update and install prometheus
  ansible.builtin.package:
    name: prometheus
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Prometheus args
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus

- name: Prometheus configuration file
  template:
    src: prometheus_yaml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: reload_prometheus

- name: Start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes

- name: Add Grafana rule of Uncomplicated Firewall
  community.general.ufw:
    rule: allow
    port: '{{ prometheus_port }}'
    protocol: 'tcp'
    state: enabled 
  when: ufw_open_prometheus_port