version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
     - openvpn-status:/tmp/
  openvpn_exporter:
    image: kumina/openvpn-exporter
    container_name: openvpn-exporter
    command: -openvpn.status_paths /etc/openvpn_exporter/openvpn-status.log
    ports:
     - 9176:9176
    restart: always
    volumes:
     - openvpn-status:/etc/openvpn_exporter/
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  grafana:
      image: grafana/grafana:7.5.7
      ports:
        - 3000:3000
      restart: unless-stopped
      volumes:
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        - grafana-data:/var/lib/grafana
volumes:
  openvpn-status:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
