---
  - name: Install Dependencies
    ansible.builtin.package:
      name: 
        - git
      state: present
  
  - name: Install Golang
    snap:
      name: go
      classic: yes

  - name: Creates OpenVPN directory
    file:
      path: /var/lib/openvpn_exporter
      state: directory  
      
  - name: Clone OpenVPN Exporter
    git:
      repo: https://github.com/kumina/openvpn_exporter.git
      dest: ./openvpn_exporter
      clone: yes
      update: yes    

  - name: Build OpenVPN Exporter
    ansible.builtin.command:
      chdir: ./openvpn_exporter
      cmd: go build -o openvpn_exporter
    changed_when: true

  - name: Stat OpenVpn Exporter
    stat: path=openvpn_exporter
    register: openvpn_exporter

  - name: Move OpenVpn Exporter to lib
    command: mv ./openvpn_exporter/openvpn_exporter /var/lib/openvpn_exporter
    when: openvpn_exporter.stat.exists

  - name: Cleaning Directory
    ansible.builtin.file:
      path: ./openvpn_exporter
      state: absent

  - name: Install Exporter Serivce
    ansible.builtin.template:
      src: exporter_service.j2
      dest: /etc/systemd/system/openvpn_exporter.service
      mode: '644'

  - name: Start OpenVPN Exporter Service
    systemd: state=started name=openvpn_exporter daemon_reload=yes
