---
- name: Configure pi-hole FTL
  become: true
  ansible.builtin.template:
    src: srv/ovpn/pihole/templates/pihole-FTL.conf.j2
    dest: /srv/ovpn/pihole/templates/pihole-FTL.conf
    mode: 0644
  notify:
    - Restart pihole-FTL
  tags:
    - pihole
    - configure

- name: Configure pi-hole local DNS records
  become: true
  ansible.builtin.template:
    src: srv/ovpn/pihole/templates/custom.list.j2
    dest: /srv/ovpn/pihole/templates/custom.list
    mode: 0644
  when: pi_hole_local_dns_records is defined and pi_hole_local_dns_records | length > 0
  notify:
    - Restart pihole-FTL
  tags:
    - pihole
    - configure