---
  - name: Install Dependencies
    ansible.builtin.package:
      name: 
        - git
      state: present

  - name: Install Golang
    snap:
      name: go
      classic: yes

  - name: Clone Pi-Hole Exporter
    git:
      repo: https://github.com/eko/pihole-exporter.git
      dest: ./pihole-exporter
      clone: yes
      update: yes        

  - name: Build Pihole Exporter
    ansible.builtin.command:
      chdir: ./pihole-exporter
      cmd: go build -o pihole-exporter
    changed_when: true

  - name: Stat Pihole Exporter
    stat: path=pihole-exporter
    register: pihole-exporter

  - name: Move Pihole Exporter to lib
    command: mv ./pihole-exporter/pihole-exporter /var/lib/pihole-exporter
    when: pihole-exporter.stat.exists

  - name: Cleaning Directory
    ansible.builtin.file:
      path: ./pihole-exporter
      state: absent

  - name: Install Exporter Serivce
    ansible.builtin.template:
      src: pihole-exporter.j2
      dest: /etc/systemd/system/pihole-exporter.service
      mode: '644'

  - name: Start Pihole Exporter Service
    systemd: state=started name=pihole-exporter daemon_reload=yes
  
  - name: Creates Dashboard Provider directory
    file:
      path: "{{ grafana_dashboard_provider_path }}"
    state: directory    

  - name: Add Pihole Dashboard
    copy:
      src: grafana_dashboard_pihole.json
      dest: "{{ grafana_dashboard_provider_path }}/grafana_dashboard_pihole.json"
    notify: restart_grafana