---
- name: Configure netdata
  become: true
  ansible.builtin.template:
    src: netdata.conf.j2
    dest: /etc/netdata/netdata.conf
    mode: 0644
  notify:
    - Restart netdata
  tags:
    - netdata
    - configure

- name: Creates Dashboard Provider directory
  file:
    path: "{{ grafana_dashboard_provider_path }}"
    state: directory    

- name: Add NetData Dashboard
  copy:
    src: grafana_dashboard_netdata.json
    dest: "{{ grafana_dashboard_provider_path }}/grafana_dashboard_netdata.json"
  notify: restart_grafana